[package]
name = "scx_utils"
version = "1.0.1"
edition = "2021"
authors = ["Tejun Heo <tj@kernel.org>"]
license = "GPL-2.0-only"
repository = "https://github.com/sched-ext/scx"
description = "Utilities for sched_ext schedulers"

[dependencies]
anyhow = "1.0"
bitvec = { version = "1.0", features = ["serde"] }
# FIXME - We need to allow both 0.68 and 0.69 to accommodate fedora. See the
# comment in BpfBuilder::bindgen_bpf_intf() for details.
bindgen = ">=0.68, <0.70"
glob = "0.3"
hex = "0.4.3"
lazy_static = "1.4"
libbpf-cargo = "0.23"
libbpf-rs = "0.23"
log = "0.4"
paste = "1.0"
regex = "1.10"
sscanf = "0.4"
tar = "0.4"
walkdir = "2.4"
version-compare = "0.1"
metrics = "0.23.0"
metrics-util = "0.17.0"

[build-dependencies]
bindgen = ">=0.68, <0.70"
tar = "0.4"
vergen = { version = "8.0.0", features = ["cargo", "git", "gitcl"] }
walkdir = "2.4"
